### ISSUE TITLE
大数据量导出存在内存溢出隐患

### ISSUE THREAD

**Issue by jxjyzzc** [gsh199449/spider#13]
如果数据量过大，很有可能造成程序崩溃。

**Comment by gsh199449** [comment]
请具体说下内存泄露的点是那块？当时的场景是什么？

**Comment by jxjyzzc** [comment]
![default](https://cloud.githubusercontent.com/assets/11594583/21599577/b084de42-d1a9-11e6-81cb-a010964146eb.png)
如图，如果抓取的数据量过大，导出json时，程序应该会占用很多内存导致卡死。我自己的电脑导出10万左右的数据一直无响应

**Comment by gsh199449** [comment]
后台报错了吗？如果没有应该是正在整合数据，如报错请截图给我看下。

**Comment by jxjyzzc** [comment]
没有报错，但是很卡，不得不强制停止程序了

**Comment by gsh199449** [comment]
那不是内存溢出，是正在准备数据，因为数据量大， 得多等会。

**Comment by jxjyzzc** [comment]
![image](https://cloud.githubusercontent.com/assets/11594583/21686041/ceefd2b4-d39e-11e6-9baf-373f22097d63.png)
溢出截图

**Comment by gsh199449** [comment]
很抱歉当时关闭了这个issue，近期将排查。

**Comment by gsh199449** [comment]
已在 2ba62ba 中修复
