### ISSUE TITLE
能提供Docker环境么？

### ISSUE THREAD

**Issue by hurricanetx** [gsh199449/spider#14]
能提供Docker环境么？

**Comment by gsh199449** [comment]
我对docker不熟，如果你熟悉的话可以提交pr。

**Comment by nisang** [comment]
docker 环境我可以提供。现在我这编译失败。

**Comment by gsh199449** [comment]
怎么编译失败？

**Comment by nisang** [comment]
启用es搜索引擎，启动项目，在ESClient.getClient()中，`final ClusterHealthResponse healthResponse = client.admin().cluster().prepareHealth()
                    .setTimeout(TimeValue.timeValueMinutes(1)).execute().actionGet();`这段代码执行失败。

**Comment by gsh199449** [comment]
报什么错

**Comment by gsh199449** [comment]
版本不对肯定是无法启动的，必须是5.0版本

**Comment by code4craft** [comment]
很棒的想法，可以弄弄！

**Comment by gsh199449** [comment]
@code4craft docker不太熟，整了两回了，都失败了

**Comment by gsh199449** [comment]
已实现，参考： https://gsh199449.github.io/gather_platform_pages/%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2.html
