### ISSUE TITLE
Mac下IDEA 源码启动请求ES异常

### ISSUE THREAD

**Issue by zzvv** [gsh199449/spider#16]
需要本地ES在```elasticsearch.yml```配置文件中加入```network.host: 127.0.0.1``` 和```network.publish_host: 127.0.0.1``` 参数配置，方可解决。

**Comment by gsh199449** [comment]
问题是什么？

**Comment by zzvv** [comment]
不显示配置ip地址，无法通过es java api 发起调用，自然无法启动工程。

**Comment by gsh199449** [comment]
你的ES和这个tomcat不是在一台机器上吧？如果不是在一台机器上可能需要配置。这不是一个bug吧？

**Comment by zzvv** [comment]
同一台机器的。不是BUG，只是提醒下，怕后面的人遇见坑。 - -抱歉

**Comment by gsh199449** [comment]
好的，谢谢
