### ISSUE TITLE
owner 我现在想做列表的爬虫抓取和列表中链接信息页数据抓取

### ISSUE THREAD

**Issue by EdronCai** [gsh199449/spider#2]
http://cs.58.com/zhaozu/pn1/pve_1092_1/?PGTID=0d30000d-0019-e4b5-3eff-f37b576ebd78&ClickID=1
你好 这个是58求租页的抓取
http://cs.58.com/zhaozu/27966561338700x.shtml?psid=175333501193992205461587821&entinfo=27966561338700_0&iuType=p_1&PGTID=0d30000d-0019-e7ad-0e33-37b8a66da82f&ClickID=1
这个是其中一个信息页的抓取
求帮忙实现哦

**Comment by gsh199449** [comment]
与项目无关，建议群里讨论下吧，issues关闭了
