### ISSUE TITLE
每次更新已有模板，都会创建一个新的模板

### ISSUE THREAD

**Issue by code4craft** [gsh199449/spider#4]
每次更新已有模板，都会新建一个新的模板ID，这是故意所为？
对于修改还是不太友好啊，特别是测试阶段可能会保存很多次。
另外，已经跑通了，分分钟抓一个站，非常赞！

**Comment by gsh199449** [comment]
是不是修改了其中的什么配置导致了两个模板不equal?

**Comment by code4craft** [comment]
嗯，是的，比如抓了一半，修改一下参数想要重新抓。
我理解其实传入ID的时候可以直接update。

**Comment by gsh199449** [comment]
恩 对,当指定id时应该走update,这个应该改下
