### ISSUE TITLE
owenr 你好 请问 webmagic 如何 和 spring 整合在一起使用？

### ISSUE THREAD

**Issue by EdronCai** [gsh199449/spider#6]
owenr 你好 请问 webmagic 如何 和 spring 整合在一起使用？

**Comment by gsh199449** [comment]
Gather Platform这个系统就是spring和webmagic做的,你这个问题太宽泛了,建议你看下我的源码.

**Comment by EdronCai** [comment]
@gsh199449  好的 我先看看
