### ISSUE TITLE
建议idea工程相关的文件要ignore

### ISSUE THREAD

**Issue by cranehe** [gsh199449/spider#8]
现在工程里clone下来会有idea的工程配置文件，建议添加到gitignore里面

**Comment by gsh199449** [comment]
这块是有意为之，方便使用idea的同学二次开发

**Comment by cranehe** [comment]
不知道这个idea里面有哪些特殊的配置，请赐教

**Comment by gsh199449** [comment]
有个这个文件夹就可以直接导入idea吧？本意就是为了方便开发的

**Comment by cranehe** [comment]
貌似根目录下还多了个idea工程的iml配置文件
